### ISSUE TITLE
Provide ansible playbook for deploying a Kubernetes Cluster

### ISSUE THREAD

**Issue by fatrix** [sahlinet/tumbo-server#26]

**Comment by fatrix** [comment]
Done in https://github.com/sahlinet/kubernetes-digitalocean

**Comment by fatrix** [comment]
Deployment of Tumbo to Cluster done in tumbo-cli.py.

**Comment by philipsahli** [comment]
Is off scope in Tumbo's Project. One might start a Kubernetes Cluster with https://stackpoint.io/.
